language: node_js

node_js:
    - "stable"
    - "7"
    - "6"
    - "5"
    - "4"
    - "0.12"
    - "0.10"

os:
    - linux

env:
    - NODE_ENV=TEST

install:
    - npm install

script:
    - npm run help
    - npm run versions-all
