language: node_js

node_js:
    - "stable"
    - "8"
    - "7"
    - "6"
    - "5"
    - "4"

addons:
    sonarcloud:
        organization: "sridharmallela-github"
        token:
            secure: "mvH/PNRZknupTiTKJy6TwETi4inB8R4NGbBukDjfQLIx79PrYkosHsr9un6vNh+4FDqev+tDBPZvJSicsEC3M5Q9whPHupC5/8unKsr8WWDgvvwVOyVwYxpI5kdqMezJGEo0NZd1t7oX+uzjQftTb1qDGolwe4z3yPsrCYVuxRSnSr83twqAMTnfIOyfLPdvHz9GCjYHUuntxRPWJ1IMNhLD5psbMTOyHz+EVkPkQ0pArXiDyU8Z/ncfa38ULv0Iuqlkv0huH/cZptfB9i7oamH3rywI3KTnaD6yJHKXhjLgXjz1cIfeLokOZ1t4WKOmfLKcpmdH0t0ptW3GXZnEePBK4x+GGoIKQBuU3A84UhnL9Hhkv1KGne3qUQnvyLBlKlzjWv9mZWffKXA4JfJ+5LACFOBnPa2maU5Rp92aD8YxzfM/am5rZqnWccBbxX8VGDwr9bg4G6kkN1a8a1diXRgdaYFu+fnblqgxqgWhoiKsFjRg+YaDCF2qu3vbXWhXZk/yWCi9HtEpO/wsBg8qBlM61+fhSd6/5CGttM7peeklxmz2LwRXjRjmQw+DFnTQZsCocOiZujUiLYoBOmjhHSt5JewcamzbIYKFEPPRUGR/cR0LSnWb32yphq27DarMXI53S/n1iTgMnPwECJhCI5sDKkG6VMF6LgT/r7r8qKw="
        branches:
            - master

branches:
    only:
        - master

env:
    - NODE_ENV=TEST

install:
    - npm install

script:
    - npm run check-all
    - npm run coverage
    - sonar-scanner

cache:
    directories:
        - "$HOME/.sonar/cache"
        - "node_modules"

notifications:
  email:
    on_failure: change
